### ISSUE TITLE
Entities aren't populating

### ISSUE THREAD

**Issue by jbleyleSF** [cseymourSF/RecordViewerNative#3]
<img width="888" alt="screen shot 2017-09-21 at 5 49 19 pm" src="https://user-images.githubusercontent.com/32077211/30725509-1bde56aa-9efa-11e7-95e4-e4bb9854c350.png">

**Comment by bleyle** [comment]
blitz04
jb@uiapi.org test1234
3MVG9Iu66FKeHhIP2gj7Oz2VM5b8m_ZmRV6OVnKuIy1KoKfpbQvAQnZ5xxg5gFGetjuLw3LhCIYroXuyc_T4J
https://localhost:8443/oauth-redirect
Whitelist:
https://*.herokuapp.com	
https://localhost
